### PR TITLE
fix(tracer): add http mapping attributes to transformer

### LINKED ISSUE #214: http attributes are not mapped accordingly
The trace exporter does not export HTTP attributes to a right format compatible with google (https://cloud.google.com/trace/docs/reference/v2/rest/v2/Attributes)

### What version of OpenTelemetry are you using?
0.13.0

### What version of Node are you using?
v14.15.1

### What did you do?
using this code in tracing.js:
```
'use strict';
const {LogLevel, ConsoleLogger} = require('@opentelemetry/core');
const {NodeTracerProvider} = require('@opentelemetry/node');
const {SimpleSpanProcessor} = require('@opentelemetry/tracing');
const {TraceExporter} = require('@google-cloud/opentelemetry-cloud-trace-exporter');
const traceLogger = new ConsoleLogger(LogLevel.DEBUG);
const exporter = new TraceExporter({
  logger: traceLogger
});
const provider = new NodeTracerProvider({logLevel: LogLevel.DEBUG});
provider.addSpanProcessor(new SimpleSpanProcessor(exporter));
provider.register();
```
my package.json:
```
    "@google-cloud/opentelemetry-cloud-trace-exporter": "0.7.0",
    "@opentelemetry/tracing": "0.13.0",
    "@opentelemetry/core": "0.13.0",
    "@opentelemetry/node": "0.13.0",
    "@opentelemetry/plugin-http": "0.13.0",
    "@opentelemetry/plugin-https": "0.13.0",
    "@opentelemetry/plugin-mongodb": "0.11.0"
```
I started my HTTP server and created some GET and POST requests to the server.

### What did you expect to see?
I expected to see `/http/method` and `/http/status_text` as labels

### What did you see instead?
But I see 
Screenshot from 2020-12-16 11-08-03

### Related ticket
It seems that the issue is fixed in https://github.com/census-instrumentation/opencensus-node/issues/651 but not in this repository.
### Suggestion:
expose a method on the exporter so I can define my own mapping and change the attribute name of each propery that is important for me. for example like this:
```
const exporter = new TraceExporter({
  customMapping: (fieldName) => {
    const regex = /\./gi;
    return '/'+fieldName.replaceAll(regex, '/');
  }
});
```

### PR DESCRIPTION
**Pull request by sinoohe**
Fixes #214
list of all http attributes are here: https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/semantic_conventions/http.md#common-attributes
I tried to add all of them
also note that in python they did it in this way:
https://github.com/GoogleCloudPlatform/opentelemetry-operations-python/blob/c3772de4cf50950f1d51685ff3bbf0e46ee026df/opentelemetry-exporter-google-cloud/src/opentelemetry/exporter/cloud_trace/__init__.py#L367

### CODE REVIEW

File: packages/opentelemetry-cloud-trace-exporter/src/transform.ts [hunk 1]
```diff
@@ -147,3 +147,35 @@ function valueToAttributeValue(
       return {};
   }
 }
+
+const HTTP_ATTRIBUTE_MAPPING: {[key: string]: string} = {
```
Comment (aabmass) [inline packages/opentelemetry-cloud-trace-exporter/src/transform.ts:151]: The python impl you found was done most recently, and I think has the best mapping we can do right now. I need to get with the Cloud Trace folks to finalize these. Quite a few of the ones here don't appear in https://cloud.google.com/trace/docs/reference/v1/rest/v1/projects.traces#get. Did they actually work?

File: packages/opentelemetry-cloud-trace-exporter/src/transform.ts [hunk 2]
```diff
@@ -147,3 +147,35 @@ function valueToAttributeValue(
...
+  'http.method': '/http/method',
+  'http.url': '/http/url',
+  'http.target': '/http/target',
```
Comment (aabmass) [inline packages/opentelemetry-cloud-trace-exporter/src/transform.ts:154]: not in https://cloud.google.com/trace/docs/reference/v1/rest/v1/projects.traces#get

File: packages/opentelemetry-cloud-trace-exporter/src/transform.ts [hunk 3]
```diff
@@ -147,3 +147,35 @@ function valueToAttributeValue(
...
+  'http.scheme': '/http/client_protocol',
+  'http.status_code': '/http/status_code',
+  'http.flavor': '/http/flavor',
+  'http.user_agent': '/http/user_agent',
+  'http.request_content_length': '/http/request_content_length',
+  'http.request_content_length_uncompressed':
+    '/http/request_content_length_uncompressed',
+  'http.response_content_length': '/http/response_content_length',
+  'http.response_content_length_uncompressed':
+    '/http/response_content_length_uncompressed',
```
Comment (aabmass) [inline packages/opentelemetry-cloud-trace-exporter/src/transform.ts:165]: not in https://cloud.google.com/trace/docs/reference/v1/rest/v1/projects.traces#get

In the python impl we mapped these to `/http/(request|response)/size` https://github.com/GoogleCloudPlatform/opentelemetry-operations-python/blob/c3772de4cf50950f1d51685ff3bbf0e46ee026df/opentelemetry-exporter-google-cloud/src/opentelemetry/exporter/cloud_trace/__init__.py#L373-L374

File: packages/opentelemetry-cloud-trace-exporter/src/transform.ts [hunk 4]
```diff
@@ -147,3 +147,35 @@ function valueToAttributeValue(
...
+  'http.server_name': '/http/server_name',
```
Comment (aabmass) [inline packages/opentelemetry-cloud-trace-exporter/src/transform.ts:166]: not in https://cloud.google.com/trace/docs/reference/v1/rest/v1/projects.traces#get

File: packages/opentelemetry-cloud-trace-exporter/src/transform.ts [hunk 5]
```diff
@@ -147,3 +147,35 @@ function valueToAttributeValue(
...
+  'http.route': '/http/route',
+  'http.client_ip': '/http/client_ip',
```
Comment (aabmass) [inline packages/opentelemetry-cloud-trace-exporter/src/transform.ts:168]: not in https://cloud.google.com/trace/docs/reference/v1/rest/v1/projects.traces#get

File: packages/opentelemetry-cloud-trace-exporter/src/transform.ts [hunk 6]
```diff
@@ -147,3 +147,35 @@ function valueToAttributeValue(
...
+  'http.path': '/http/path',
```
Comment (aabmass) [inline packages/opentelemetry-cloud-trace-exporter/src/transform.ts:169]: This one's not in https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/semantic_conventions/http.md#common-attributes

**Review by aabmass — CHANGES_REQUESTED** [review]
Thanks for the PR, just a few comments

**Comment by sinoohe** [comment]
@aabmass I removed all additional fields. it's now the same as python's implementation

**Review by aabmass — APPROVED** [review]
Awesome, thanks again!
