### PR TITLE
fix: uncaught rejected promise error in MetricExporter's export method

### LINKED ISSUE #254: MetricExporter.export signature doesn't match the base class
Please answer these questions before submitting a bug report.

### What version of OpenTelemetry are you using?
@opentelemetry/metrics: ^0.18.2
@google-cloud/opentelemetry-cloud-monitoring-exporter: ^0.9.0

### What version of Node are you using?
v12.20.2

### What did you do?
If possible, provide a recipe for reproducing the error.

The MetricExporter implementation's export definition does not match the base class it's implementing. The base class signature does not return a Promise<void>. However, there is an [open issue](https://github.com/open-telemetry/opentelemetry-js/issues/1023) to support returning a promise. Having these functions not match up causes a Typescript compilation issue and ignoring it causes a dangling promise error. 

I'm referencing line 94 in [packages/opentelemetry-cloud-monitoring-exporter/src/monitoring.ts](https://github.com/GoogleCloudPlatform/opentelemetry-operations-js/blob/103e0a4426560bd9a8cc932af2f03a889f2bd1fe/packages/opentelemetry-cloud-monitoring-exporter/src/monitoring.ts#L94):

```
async export(
    metrics: MetricRecord[],
    cb: (result: ExportResult) => void
  ): Promise<void> {
```

The base class is [MetricExporter from opentelemetry/opentelemetry-metrics](https://github.com/open-telemetry/opentelemetry-js/blob/897c35f497363ee3f3ea4c1e5ad1628e09ec9041/packages/opentelemetry-metrics/src/export/types.ts#L95):

```
export interface MetricExporter {
  /** Exports the list of a given {@link MetricRecord} */
  export(
    metrics: MetricRecord[],
    resultCallback: (result: ExportResult) => void
  ): void;

  /** Stops the exporter. */
  shutdown(): Promise<void>;
}
```

### PR DESCRIPTION
**Pull request by seanachai**
Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [X] Make sure to open an issue as a [bug/issue/feature](https://github.com/GoogleCloudPlatform/opentelemetry-operations-js/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [X] Ensure the tests and linter pass
- [X] Code coverage does not decrease (if any source code was changed)
- [X] Appropriate docs were updated (if necessary)

Fixes #254

### CODE REVIEW

**Comment by seanachai** [comment]
@googlebot I signed it!

File: packages/opentelemetry-cloud-monitoring-exporter/src/monitoring.ts [hunk 1]
```diff
@@ -93,7 +93,13 @@ export class MetricExporter implements IMetricExporter {
     cb: (result: ExportResult) => void
   ): Promise<void> {
     if (this._projectId instanceof Promise) {
-      this._projectId = await this._projectId;
+      try {
```
Comment (aabmass) [inline packages/opentelemetry-cloud-monitoring-exporter/src/monitoring.ts:96]: Nice! I think the await on L114 could also throw. Maybe we could do something like this to generalize:

```ts
  async _exportAsync(
    metrics: MetricRecord[],
  ): Promise<ExportResult> {
    // this comes from renaming and updating params for the existing export() function
    // and instead return the ExportResult
  }
  
  export(
    metrics: MetricRecord[],
    cb: (result: ExportResult) => void
  ): void {
    _exportAsync(metrics)
      .then(cb)
      .except(err => {
        diag.error(err.message);
        cb(/* map err to ExportResult */);
      });
  }
```

Comment (seanachai) [reply packages/opentelemetry-cloud-monitoring-exporter/src/monitoring.ts:96]: Oh wow yeah great catch. I totally missed the await on L114. Great idea on wrapping the async calls in their own function. I'll get on that asap.

Comment (seanachai) [reply packages/opentelemetry-cloud-monitoring-exporter/src/monitoring.ts:115]: @aabmass apologies for the delay here. Lmk how this looks. I added some comments for clarity. I'm happy to add some more tests too if necessary.

Comment (aabmass) [reply packages/opentelemetry-cloud-monitoring-exporter/src/monitoring.ts:115]: No worries. I think you can remove this new try block since it will be caught in the `.catch()` above.

File: packages/opentelemetry-cloud-monitoring-exporter/src/monitoring.ts [hunk 2]
```diff
@@ -92,14 +93,38 @@ export class MetricExporter implements IMetricExporter {
     metrics: MetricRecord[],
     cb: (result: ExportResult) => void
   ): Promise<void> {
+    return this._exportAsync(metrics)
```
Comment (aabmass) [inline packages/opentelemetry-cloud-monitoring-exporter/src/monitoring.ts:96]: This function doesn't need to be async anymore

File: packages/opentelemetry-cloud-monitoring-exporter/src/monitoring.ts [hunk 3]
```diff
@@ -92,14 +93,38 @@ export class MetricExporter implements IMetricExporter {
...
+        return cb({code: ExportResultCode.FAILED, error: err});
+      });
+  }
+
+  async shutdown(): Promise<void> {}
+
+  /**
+   * Asnyc wrapper for the {@link export} implementation.
+   * Saves the current values of all exported {@link MetricRecord}s so that
+   * they can be pulled by the Google Cloud Monitoring backend.
```
Comment (aabmass) [inline packages/opentelemetry-cloud-monitoring-exporter/src/monitoring.ts:109]: Just noticed this original description doesn't really make sense, there is no pulling. Can we just make it "Writes MetricRecords to Cloud Monitoring" or similar?

File: packages/opentelemetry-cloud-monitoring-exporter/test/monitoring.test.ts [hunk 4]
```diff
@@ -135,6 +135,53 @@ describe('MetricExporter', () => {
...
+      let unhandledPromiseRejectionEvent = false;
+      process.on('unhandledRejection', error => {
+        unhandledPromiseRejectionEvent = true;
+      });
+
+      const result = await new Promise<ExportResult>(resolve => {
+        exporter.export(records, result => {
+          resolve(result);
+        });
+      });
```
Comment (aabmass) [inline packages/opentelemetry-cloud-monitoring-exporter/test/monitoring.test.ts:180]: Since we are still returning the promise, this would be equivalent?

```suggestion
      const result = await exporter.export(records, () => {});
```

File: packages/opentelemetry-cloud-monitoring-exporter/test/monitoring.test.ts [hunk 5]
```diff
@@ -135,6 +135,53 @@ describe('MetricExporter', () => {
...
+
+      assert.strictEqual(unhandledPromiseRejectionEvent, false);
```
Comment (aabmass) [inline packages/opentelemetry-cloud-monitoring-exporter/test/monitoring.test.ts:182]: Did you find this test failed before the fix? I'm not sure if `unhandledRejection` handler is guaranteed to be called before this assertion is made

**Review by aabmass — COMMENTED** [review]
LGTM, just a few small comments

File: packages/opentelemetry-cloud-monitoring-exporter/test/monitoring.test.ts (hunk 5 above)
Comment (seanachai) [reply packages/opentelemetry-cloud-monitoring-exporter/test/monitoring.test.ts:182]: I wanted to make sure there was a regression test covering what we're improving. I ran this without my changes and it triggered a failure. Admittedly, I haven't used this in practice so I can't say if this is a good practice or not.

File: packages/opentelemetry-cloud-monitoring-exporter/test/monitoring.test.ts (hunk 4 above)
Comment (seanachai) [reply packages/opentelemetry-cloud-monitoring-exporter/test/monitoring.test.ts:180]: Oh yeah this makes sense. I was just following previous test patterns.

File: packages/opentelemetry-cloud-monitoring-exporter/src/monitoring.ts (hunk 2 above)
Comment (seanachai) [reply packages/opentelemetry-cloud-monitoring-exporter/src/monitoring.ts:96]: Which function?

Comment (aabmass) [reply packages/opentelemetry-cloud-monitoring-exporter/src/monitoring.ts:96]: Sorry, the `export()` function, you can just remove the `async` since it doesn't await anymore

File: packages/opentelemetry-cloud-monitoring-exporter/test/monitoring.test.ts (hunk 4 above)
Comment (aabmass) [reply packages/opentelemetry-cloud-monitoring-exporter/test/monitoring.test.ts:180]: gotcha. either way is fine with me, feel free to resolve

Comment (seanachai) [reply packages/opentelemetry-cloud-monitoring-exporter/test/monitoring.test.ts:180]: Sounds good 👍🏻 Apologies for the major delay here. May has been quite a month for me. I'll get to wrapping this up by EoW.

File: packages/opentelemetry-cloud-monitoring-exporter/test/monitoring.test.ts [hunk 6]
```diff
@@ -243,7 +289,11 @@ describe('MetricExporter', () => {
       await meter.collect();
       const records2 = meter.getProcessor().checkPointSet();
 
-      await exporter.export(records2, () => {});
+      const result2 = await new Promise<ExportResult>(resolve => {
```
Comment (seanachai) [inline packages/opentelemetry-cloud-monitoring-exporter/test/monitoring.test.ts:292]: I believe removing the async from the export function made these changes necessary.

**Comment by seanachai** [comment]
@aabmass made those latest changes. Lmk what you think 🍻

**Review by aabmass — APPROVED** [review]
Nice, thank you for the PR!

**Comment by aabmass** [comment]
@seanachai could you fix the lint warnings? I think the codecov patch check will be fixed if you rebase on master.

**Comment by seanachai** [comment]
> @seanachai could you fix the lint warnings? I think the codecov patch check will be fixed if you rebase on master.

Yup, will do 👍

**Comment by seanachai** [comment]
Thanks @aabmass!
